# Generated by Django 3.0.8 on 2020-08-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
